### ISSUE TITLE
Not getting any results

### ISSUE THREAD

**Issue by Iron-E** [f3fora/cmp-spell#1]
If I only enable `sources = {{name = 'spell'}}`, no suggestions are shown.

**Comment by Arrow-x** [comment]
![Screenshot_2021-10-09_10-49-46](https://user-images.githubusercontent.com/3308421/136653403-8f90f1e4-61fc-4ae6-8dca-38631ca23c0e.png)
everything else seems to work though

**Comment by Arrow-x** [comment]
![Screenshot_2021-10-09_10-49-46](https://user-images.githubusercontent.com/3308421/136653924-85be92c3-3a23-4887-acbe-5a964e89728d.png)

everything else seems to work though

**Comment by Iron-E** [comment]
> Have you set spell and spelllang?

I have `spellang` set. I'll follow up today or tomorrow with whether `spell` affects it.

**Comment by Iron-E** [comment]
Yeah, seems to work with `set spell` on

**Comment by BitInByte** [comment]
Hey, I have setup everything as you told and I can't get Spell on almost any file :( don't know If I'm setting something wrong in my config

**Comment by edte** [comment]
I'm having the same problem, the default cmp source doesn't have a complementary box, only after pressing c-x, c-s

behavior

the result of CmpStatus
<img width="499" alt="截屏2024-01-31 18 42 59" src="https://github.com/f3fora/cmp-spell/assets/50194671/f5af703a-e100-4d4b-880b-ad770f41a453">


no
<img width="363" alt="截屏2024-01-31 18 40 23" src="https://github.com/f3fora/cmp-spell/assets/50194671/e1958c6a-1291-44ec-a636-65fe60b51c5f">
after press c-x,c-s
<img width="284" alt="截屏2024-01-31 18 40 35" src="https://github.com/f3fora/cmp-spell/assets/50194671/4e864275-d0ea-47f6-b7c7-3d2192992c0e">


myconfig

plugin install
<img width="498" alt="截屏2024-01-31 18 37 27" src="https://github.com/f3fora/cmp-spell/assets/50194671/e9353526-3308-4f41-ac69-967b51a07e15">
cmp config
<img width="506" alt="截屏2024-01-31 18 37 52" src="https://github.com/f3fora/cmp-spell/assets/50194671/0c0bce34-cd0a-4b31-bd9f-7883ec55d6c0">
option config
<img width="465" alt="截屏2024-01-31 18 38 42" src="https://github.com/f3fora/cmp-spell/assets/50194671/d2c9b661-a3b0-44d1-8142-c4dd9bc5d4f6">
lunarvim
<img width="586" alt="截屏2024-01-31 18 39 03" src="https://github.com/f3fora/cmp-spell/assets/50194671/e4163c51-478d-45e0-8fbe-8e223e66e21e">
