### ISSUE TITLE
cmp-spell source is always first selected

### ISSUE THREAD

**Issue by shy-robin** [f3fora/cmp-spell#10]
This is my cmp sources:
```
      sources = cmp.config.sources({
        { name = "nvim_lsp" },
        { name = "luasnip" },
        { name = "buffer" },
        { name = "spell" },
        { name = "path" },
      }),
```
When I input text, lsp source should be on the top of popup menu,  but I got spell source first:
<img width="711" alt="image" src="https://github.com/f3fora/cmp-spell/assets/59857729/7c166021-e00c-4bd4-8e19-4c97821df7a4">
Is there something wrong with priority of spell source?
When I remove spell source, I got this:
<img width="719" alt="image" src="https://github.com/f3fora/cmp-spell/assets/59857729/2871f39b-af1e-4a8a-850b-04b596ba8e25">
It seems to be normal.

**Comment by pimvh** [comment]
Hi! This is probably not an issue with this plugin, you can set priority of your completions like the following:

```
         { name = "nvim_lua", priority = 10 }, 
         { name = "nvim_lsp_signature_help", priority = 10 }, 
         { name = "path", priority = 10 },
         -- Supplementary 
         { name = "dictionary", priority = 5, max_item_count = 4, keyword_length = 2 }, 
         { 
             name = "spell", 
             priority = 5,  --                  <<<< like this
             max_item_count = 2, 
             keyword_length = 2, 
             option = { keep_all_entries = true }, 
         },

```

By setting the priority of `spell` to a lower value, the ordering should change.

**Comment by shy-robin** [comment]
> priority = 10

Thanks for your reply. I changed the priority of sources, but it does not work.
```
      sources = cmp.config.sources({
        { name = "nvim_lsp", priority = 10 },
        { name = "luasnip", priority = 8 },
        { name = "buffer", priority = 6 },
        { name = "spell", priority = 4 },
        { name = "path", priority = 2 },
      }),
```
<img width="712" alt="image" src="https://github.com/f3fora/cmp-spell/assets/59857729/711bbd5d-233d-4381-b04e-5a740f5ec019">

**Comment by pimvh** [comment]
Let's see...  

I remember having this issue a while ago too, and I think editing the sorting parameter(s) helped. 

I have the following sorting defined: 

``` 
    sorting = {
        priority_weight = 2,
        comparators = {
            cmp.config.compare.locality,
            cmp.config.compare.recently_used,
            cmp.config.compare.score, -- final_score = orig_score + ((#sources - (source_index - 1)) * sorting.priority_weight) (priority_weight = sources[n].priority
            cmp.config.compare.offset,
            cmp.config.compare.exact,
            -- cmp.config.compare.kind,
            cmp.config.compare.sort_text,
            -- cmp.config.compare.length,
            -- cmp.config.compare.order,
        },
    },
```

This might work. Aside, I have nothing in my config that would change this afaik.

Please report back, it might be useful to document this for other users.

**Comment by shy-robin** [comment]
> Let's see...
> 
> I remember having this issue a while ago too, and I think editing the sorting parameter(s) helped.
> 
> I have the following sorting defined:
> 
> ```
>     sorting = {
>         priority_weight = 2,
>         comparators = {
>             cmp.config.compare.locality,
>             cmp.config.compare.recently_used,
>             cmp.config.compare.score, -- final_score = orig_score + ((#sources - (source_index - 1)) * sorting.priority_weight) (priority_weight = sources[n].priority
>             cmp.config.compare.offset,
>             cmp.config.compare.exact,
>             -- cmp.config.compare.kind,
>             cmp.config.compare.sort_text,
>             -- cmp.config.compare.length,
>             -- cmp.config.compare.order,
>         },
>     },
> ```
> 
> This might work. Aside, I have nothing in my config that would change this afaik.
> 
> Please report back, it might be useful to document this for other users.

I use this config and it can change the order of sources. But there is another problem, when I input something, it will choose the cmp-spell source automatically, but not the first suggestion.
![image](https://github.com/f3fora/cmp-spell/assets/59857729/063bfea0-7f19-4b66-9b09-38a27f541f95)

**Comment by pimvh** [comment]
> > Let's see...
> > 
> > I remember having this issue a while ago too, and I think editing the sorting parameter(s) helped.
> > 
> > I have the following sorting defined:
> > 
> > ```
> >     sorting = {
> >         priority_weight = 2,
> >         comparators = {
> >             cmp.config.compare.locality,
> >             cmp.config.compare.recently_used,
> >             cmp.config.compare.score, -- final_score = orig_score + ((#sources - (source_index - 1)) * sorting.priority_weight) (priority_weight = sources[n].priority
> >             cmp.config.compare.offset,
> >             cmp.config.compare.exact,
> >             -- cmp.config.compare.kind,
> >             cmp.config.compare.sort_text,
> >             -- cmp.config.compare.length,
> >             -- cmp.config.compare.order,
> >         },
> >     },
> > ```
> > 
> > This might work. Aside, I have nothing in my config that would change this afaik.
> > 
> > Please report back, it might be useful to document this for other users.
> 
> I use this config and it can change the order of sources. But there is another problem, when I input something, it will choose the cmp-spell source automatically, but not the first suggestion.
> ![image](https://github.com/f3fora/cmp-spell/assets/59857729/063bfea0-7f19-4b66-9b09-38a27f541f95)
> 

Have you set the options in the cmp completion source, for example the attribute where it keeps all entries? (see above)

**Comment by shy-robin** [comment]
@pimvh This is my nvim-cmp config (I use lazy.nvim):
```
return {
  "hrsh7th/nvim-cmp",
  dependencies = {
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-path",
    "saadparwaiz1/cmp_luasnip",
    "hrsh7th/cmp-cmdline",
    "f3fora/cmp-spell"
  },
  opts = function()
    local defaults = require("cmp.config.default")()
    local cmp = require("cmp")

    -- `/` cmdline setup.
    ---@diagnostic disable-next-line: missing-fields
    cmp.setup.cmdline('/', {
      window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      },
      mapping = cmp.mapping.preset.cmdline(),
      sources = {
        { name = 'buffer' }
      }
    })

    -- `:` cmdline setup.
    ---@diagnostic disable-next-line: missing-fields
    cmp.setup.cmdline(':', {
      window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      },
      mapping = cmp.mapping.preset.cmdline(),
      sources = cmp.config.sources({
        { name = 'path' }
      }, {
        {
          name = 'cmdline',
          option = {
            ignore_cmds = { 'Man', '!' }
          }
        }
      })
    })

    return {
      window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      },
      completion = {
        completeopt = "menu,menuone,noinsert",
      },
      snippet = {
        expand = function(args)
          require("luasnip").lsp_expand(args.body)
        end,
      },
      mapping = cmp.mapping.preset.insert({
        ["<C-j>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
        ["<C-k>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
        ["<C-u>"] = cmp.mapping.scroll_docs(-4),
        ["<C-d>"] = cmp.mapping.scroll_docs(4),
        ["<C-Space>"] = cmp.mapping.complete(),
        ["<C-e>"] = cmp.mapping.abort(),
        ["<Tab>"] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
        ["<CR>"] = cmp.mapping.confirm({ select = false }),
        ["<S-CR>"] = cmp.mapping.confirm({
          behavior = cmp.ConfirmBehavior.Replace,
          select = true,
        }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
      }),
      sources = cmp.config.sources({
        { name = "nvim_lsp", priority = 10 },
        { name = "luasnip",  priority = 8 },
        { name = "buffer",   priority = 6 },
        { name = "spell",    priority = 4 },
        { name = "path",     priority = 2 },
      }),
      formatting = {
        format = function(entry, item)
          local icons = require("lazyvim.config").icons.kinds
          if icons[item.kind] then
            item.kind = icons[item.kind] .. item.kind
            item.menu = ({
              nvim_lsp = "[LSP]",
              luasnip = "[Snippet]",
              buffer = "[Buffer]",
              spell = "[Spell]",
              path = "[Path]"
            })[entry.source.name]
          end
          return item
        end,
      },
      sorting = {
        priority_weight = 2,
        comparators = {
          cmp.config.compare.locality,
          cmp.config.compare.recently_used,
          cmp.config.compare.score,   -- final_score = orig_score + ((#sources - (source_index - 1)) * sorting.priority_weight) (priority_weight = sources[n].priority
          cmp.config.compare.offset,
          cmp.config.compare.exact,
          -- cmp.config.compare.kind,
          cmp.config.compare.sort_text,
          -- cmp.config.compare.length,
          -- cmp.config.compare.order,
        },
      },
    }
  end,
}
```
I have tried to remove cmp-spell source, and the problem is still exist. Maybe the sorting method is the main reason. 
![image](https://github.com/f3fora/cmp-spell/assets/59857729/3157f751-6404-4c73-8844-a95f91352dc6)

**Comment by f3fora** [comment]
The current implementation selects an entry if the spell is correct.

The first "preselectable" item in the source with the highest priority get selected. You can disable `preselect` in `nvim-cmp` options: `:h cmp-config.preselect`, e.g., 
```lua
cmp.setup(
{
preselect = cmp.PreselectMode.None
}
)

**Comment by shy-robin** [comment]
@f3fora Thanks a lot. It works.
