### ISSUE TITLE
\w+ only captures ASCII

### ISSUE THREAD

**Issue by rdpopov** [f3fora/cmp-spell#2]
I had a problem with non-English spelling completion.
Turns out \w+ only captures ascii characters and then cmp doesn't count them as things to complete and cancels the completion.
It is an old vim limitation, that is inherited in neovim.
Tried it with \k or \K (\K is the better one, excludes numbers) and should work regardless of language?
At least it works for both English and any Cyrilic alphabet-based language

**Comment by zakissimo** [comment]
I see this was closed, but I can't seem to get suggestions for accentuated characters ?

![Capture d’écran du 2024-04-12 10-57-34](https://github.com/f3fora/cmp-spell/assets/64891486/460659eb-0970-4967-b92c-989c47fe89c7)
![Capture d’écran du 2024-04-12 10-58-16](https://github.com/f3fora/cmp-spell/assets/64891486/7762df9d-6abf-4f8e-bf2c-571766e163a4)
![Capture d’écran du 2024-04-12 10-57-54](https://github.com/f3fora/cmp-spell/assets/64891486/93e99d54-76d7-48df-99db-7d9eb24ef053)

```lua
set.spell = true
set.spelllang = "en,fr"
set.spelloptions = "camel"
```

Am I doing something wrong ?

**Comment by rdpopov** [comment]
I'm not sure, I just noticed how vim actually represents different alphabets.
It's probably something with the patterns again. There is \p or \P for printable. But do thse fall under printable, I will check.
