### ISSUE TITLE
Suggest correction

### ISSUE THREAD

**Issue by EricDriussi** [f3fora/cmp-spell#3]
Hi there! Any way to make the extension suggest corrections for misspelled words?
Thanks a lot and keep up the good work! 💪

**Comment by f3fora** [comment]
> Any way to make the extension suggest corrections for misspelled words? Thanks a lot and keep up the good work! 

This is out of the scope of this plugin.

You can use `z=` or [telescope](https://github.com/nvim-telescope/telescope.nvim/blob/9aaaa0c5f3eb665b51bbcafda084de4b0952fef0/README.md?plain=1#L284)
