### ISSUE TITLE
Spell completions are being filtered

### ISSUE THREAD

**Issue by rwblokzijl** [f3fora/cmp-spell#6]
Using the spell extension all the suggestions from spell should be shown:

![image](https://user-images.githubusercontent.com/446634/193453068-833ee290-fba2-4cf6-82f3-fd09f6745898.png)

cmp-spell uses vim builtin spelling correction, which should return:

![image](https://user-images.githubusercontent.com/446634/193453087-af8fd3c5-dfb3-4890-acb1-3cc32ea4df95.png)

However it seems like the results are being filtered to only include fuzzy matches which defeats the point of spell correcting.

**Comment by f3fora** [comment]
is it ok for you?

**Comment by rwblokzijl** [comment]
Thanks a lot for this! It does include everything now. 

Now I just have to find out how to sort it to the bottom as it becomes very busy :p
Do you have any tips for this?

**Comment by rwblokzijl** [comment]
I opted for using `max_item_count=2`. Works pretty well
